apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: capi-mgmt-p-01
  namespace: cluster-capi-mgmt-p-01
spec:
  controlPlaneEndpoint:
    host: "10.0.0.150"
    port: 6443
  ipv4Config:
    addresses:
      - "10.0.0.155-10.0.0.169"
    prefix: 24
    gateway: "10.0.0.1"
  dnsServers:
    - "8.8.8.8"
    - "8.8.4.4"
  allowedNodes: []
  credentialsRef:
    name: proxmox-creds
