---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: proxmox
  namespace: capmox-system
spec:
  version: v0.5.1-dev
  fetchConfig:
    selector:
      matchLabels:
        provider: proxmox
